language: php

php:
    - 7.2
    - 7.3

notifications:
    email: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true

before_install:
    - echo 'Europe/Berlin' | sudo tee /etc/timezone
    - sudo dpkg-reconfigure --frontend noninteractive tzdata

before_script:
    - pecl install inotify
    - composer install --no-interaction

script:
    - composer phpcs
    - composer phpstan
    - composer phpunit 
    - php vendor/bin/php-cs-fixer fix --config .php_cs.dist --dry-run
