language: php

php:
    - 7.2
    - 7.3
    - 7.4snapshot

notifications:
    email: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    allow_failures:
        - php: "7.4snapshot"

before_install:
    - echo 'Europe/Berlin' | sudo tee /etc/timezone
    - sudo dpkg-reconfigure --frontend noninteractive tzdata
    - pecl install inotify

install:
    - composer install --no-interaction --no-suggest

script:
    - composer test:lint
    - composer test:phpstan
    - composer test:psalm
    - composer test:unit 
    - composer test:mutation
