language: php

php:
    - 7.2
    - 7.3
    - 7.4
    - nightly

notifications:
    email: false

cache:
    directories:
        - $HOME/.composer/cache

jobs:
    fast_finish: true
    allow_failures:
      - php: nightly

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"
        - PLATFORM_FLAGS=""

before_install:
    - echo 'Europe/Berlin' | sudo tee /etc/timezone
    - sudo dpkg-reconfigure --frontend noninteractive tzdata
    - |
      if [[ ${TRAVIS_PHP_VERSION} == "nightly" ]]; then
          cd /tmp
          wget https://github.com/arnaud-lb/php-inotify/archive/master.zip
          unzip master.zip
          cd php-inotify-master
          phpize
          ./configure
          make
          make install
          echo "extension=inotify.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
          cd $TRAVIS_BUILD_DIR
      else
          pecl install inotify
      fi

install:
    - if [[ ${TRAVIS_PHP_VERSION} == "nightly" ]]; then export PLATFORM_FLAGS="--ignore-platform-reqs"; fi
    - composer update $DEFAULT_COMPOSER_FLAGS $PLATFORM_FLAGS

script:
    - composer test:lint
    - composer test:phpstan
    - composer test:psalm
    - composer test:unit 
    - composer test:mutation

after_success:
    - bash <(curl -s https://codecov.io/bash)
